# Generated by Django 2.0.3 on 2019-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stweet',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
    ]
